package org.example.view;

import org.example.controller.FileHandler;
import org.example.model.FontFormat;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.filechooser.FileNameExtensionFilter;

import javax.swing.text.*;

import static javax.swing.UIManager.getInstalledLookAndFeels;
import static javax.swing.UIManager.setLookAndFeel;

/**
 * @author admin
 */

public class MainWindow extends JFrame {
    /**
     * Creates new form MainWindow
     */

    public static FontFormat fontFormatMainWindow;

    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollPane1 = new JScrollPane();
        textPaneMain = new JTextPane();
        jPanel1 = new JPanel();
        txtFont = new JLabel();
        lblFontAndSize = new JLabel();
        txtMark = new JLabel();
        txtCount = new JLabel();
        lblCountChars = new JLabel();
        jMenuBar1 = new JMenuBar();
        menuFile = new JMenu();
        menuItemNew = new JMenuItem();
        menuItemOpen = new JMenuItem();
        menuItemSave = new JMenuItem();
        menuItemSaveWith = new JMenuItem();
        menuItemExit = new JMenuItem();
//        menuOptions = new JMenu();
        menuItemFontFormat = new JMenuItem();
        menuItemAbout = new JMenuItem();

        setTitle("Editor de texto");

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        textPaneMain.setBorder(BorderFactory.createEmptyBorder(7, 7, 7, 7));
        textPaneMain.setPreferredSize(new Dimension(500, 400));
        jScrollPane1.setViewportView(textPaneMain);

        getContentPane().add(jScrollPane1, BorderLayout.CENTER);

        jPanel1.setBorder(BorderFactory.createEmptyBorder(3, 3, 3, 3));
        jPanel1.setLayout(new BoxLayout(jPanel1, BoxLayout.LINE_AXIS));

        //txtFont.setText("Fuente: ");
        //txtFont.setToolTipText("");
//        txtFont.setBorder(BorderFactory.createEmptyBorder(0, 7, 0, 0));
//        jPanel1.add(txtFont);

        //lblFontAndSize.setText("Helvetica (15)");
        lblFontAndSize.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 7));
        jPanel1.add(lblFontAndSize);

        //txtMark.setText("|");
        jPanel1.add(txtMark);

        //txtCount.setText("Carácteres: ");
        txtCount.setBorder(BorderFactory.createEmptyBorder(0, 7, 0, 0));
        jPanel1.add(txtCount);

        //lblCountChars.setText("100");
        lblCountChars.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 7));
        jPanel1.add(lblCountChars);

        getContentPane().add(jPanel1, BorderLayout.PAGE_END);

        menuFile.setText("Archivo");

        menuItemNew.setText("Nuevo");
        menuItemNew.addActionListener(this::menuItemNewActionPerformed);
        menuFile.add(menuItemNew);

        menuItemOpen.setText("Abrir");
        menuItemOpen.addActionListener(this::menuItemOpenActionPerformed);
        menuFile.add(menuItemOpen);

        menuItemSave.setText("Guardar");
        menuItemSave.addActionListener(this::menuItemSaveActionPerformed);
        menuFile.add(menuItemSave);

        menuItemSaveWith.setText("Guardar como ...");
        menuItemSaveWith.addActionListener(this::menuItemSaveWithActionPerformed);
        menuFile.add(menuItemSaveWith);

        menuItemExit.setText("Salir");
        menuItemExit.addActionListener(this::menuItemExitActionPerformed);
        menuFile.add(menuItemExit);

        jMenuBar1.add(menuFile);

//        menuOptions.setText("Opciones");

        menuItemFontFormat.setText("Formato Fuente");
        menuItemFontFormat.addActionListener(this::menuItemFontFormatActionPerformed);
//        menuOptions.add(menuItemFontFormat);

        menuItemAbout.setText("Acerca de ...");
        menuItemAbout.addActionListener(this::menuItemAboutActionPerformed);
//        menuOptions.add(menuItemAbout);

//        jMenuBar1.add(menuOptions);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>

    private void menuItemOpenActionPerformed(ActionEvent evt) {
        JFileChooser chooser = new JFileChooser();

        var filtro = new FileNameExtensionFilter("*.TXT", "txt");

        chooser.setFileFilter(filtro);

        int selection = chooser.showOpenDialog(this);

        
        if(selection == JFileChooser.APPROVE_OPTION){
            
            File file = chooser.getSelectedFile();
            
            FileHandler.savedFile = file;
            
            try(FileReader fr = new FileReader(file)){
                String s = "";
                int value = fr.read();
                while(value != -1){
                    s += (char)value;
                    value=fr.read();
                }
                this.textPaneMain.setText(s);
            }catch(IOException e){
                e.printStackTrace();
            }
        }
    }

    private void menuItemFontFormatActionPerformed(ActionEvent evt) {
        //textPaneMain.setFont(new Font("Arial", Font.PLAIN, 20));
        showFontFormat();
    }

    private void menuItemNewActionPerformed(ActionEvent evt) {
        JFileChooser fc = new JFileChooser();

        int selection = fc.showSaveDialog(this);

        if(selection == JFileChooser.APPROVE_OPTION){

            File file = fc.getSelectedFile();
            FileHandler.savedFile = file;
        }
    }

    //este es salir

    private void menuItemExitActionPerformed(ActionEvent evt){
        
        if(FileHandler.savedFile == null)            showErrorDialog();
        else{
            saveAllDatta(FileHandler.savedFile);
            System.exit(0);
        }        

    }

    private void menuItemAboutActionPerformed(ActionEvent evt) {
        showAboutDialog();
    }

    private void menuItemSaveActionPerformed(ActionEvent evt) {

        
        if(FileHandler.savedFile == null)            showErrorDialog();
        else                                         saveAllDatta(FileHandler.savedFile);
    }

    //este es el guardar como

    private void menuItemSaveWithActionPerformed(ActionEvent evt){
        
        JFileChooser fc = new JFileChooser();
 
        int selection = fc.showSaveDialog(this);

        if(selection == JFileChooser.APPROVE_OPTION){

            File file = fc.getSelectedFile();
            FileHandler.savedFile = file;

            saveAllDatta(file);            
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (UIManager.LookAndFeelInfo info : getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(() -> new MainWindow().setVisible(true));
    }

    public void showAboutDialog() {
        String message = """
                Autores:
                Pablo Jim\u00e9nez Juarez
                Miguel Mu\u00f1oz Jim\u00e9nez
                Tecnologías usadas:
                Java y swing
                """;
        String title = "Acerca de ...";
        JOptionPane.showMessageDialog(this, message, title,
                JOptionPane.PLAIN_MESSAGE);
    }

    
    public void showErrorDialog(){
        String message = """
                         ¡No hay fichero seleccionado!
                         Prueba la opción guardar como.    
                         """;
            String title = "ERROR";
            JOptionPane.showMessageDialog(this, message, title,
                    JOptionPane.ERROR_MESSAGE);
    }
    
    public void saveAllDatta(File file) {
        try(FileWriter fw = new FileWriter(file)){

            fw.write(this.textPaneMain.getText());

        } catch (IOException e1) {
            e1.printStackTrace();
        }
    }
    

    public void showFontFormat() {
        var fontFormatDialog = new FontFormatDialog(this, true);
        fontFormatDialog.setVisible(true);
        insertStyleInText();
    }

    public int getPositionCaret() {
        Caret caret = textPaneMain.getCaret();
        return caret.getDot();
    }

    public void insertStyleInText() {
        SimpleAttributeSet set = changeSimpleAttributeSet();
        Document doc = textPaneMain.getStyledDocument();

        String textToInsert = "\u202C";

        try {
            doc.insertString(getPositionCaret(), textToInsert, set);
        } catch (BadLocationException e) {
            throw new RuntimeException(e);
        }
    }

    public SimpleAttributeSet changeSimpleAttributeSet() {
        SimpleAttributeSet set = new SimpleAttributeSet();
        textPaneMain.setCharacterAttributes(set, true);

        StyleConstants.setForeground(set, FontFormat.foregroundColor);
        StyleConstants.setBackground(set, FontFormat.backgroundColor);

        StyleConstants.setFontFamily(set, FontFormat.name);
        StyleConstants.setFontSize(set, FontFormat.size);

        switch (FontFormat.style) {
            case 1:
                StyleConstants.setBold(set, true);
                break;
            case 2:
                StyleConstants.setItalic(set, true);
                break;
            case 3:
                StyleConstants.setBold(set, true);
                StyleConstants.setItalic(set, true);
                break;
            default:
                StyleConstants.setBold(set, false);
                StyleConstants.setItalic(set, false);
                break;
        }
        return set;
    }

    // Variables declaration - do not modify
    private JMenuBar jMenuBar1;
    private JPanel jPanel1;
    private JScrollPane jScrollPane1;
    private JLabel lblCountChars;
    private JLabel lblFontAndSize;
    private JMenu menuFile;
    private JMenuItem menuItemAbout;
    private JMenuItem menuItemExit;
    private JMenuItem menuItemFontFormat;
    private JMenuItem menuItemNew;
    private JMenuItem menuItemOpen;
    private JMenuItem menuItemSave;
    private JMenuItem menuItemSaveWith;
//    private JMenu menuOptions;
    private JTextPane textPaneMain;
    private JLabel txtCount;
    private JLabel txtFont;
    private JLabel txtMark;
    // End of variables declaration
}
